spring:
  application:
    name: expenses-advisor-core
  datasource:
    url: jdbc:mysql://localhost:3306/ea_core
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9001